### ISSUE TITLE
not working on Rails 3.0.2 and RSpec Rails 2.1.0

### ISSUE THREAD

**Issue by wilkerlucio** [mislav/rspec-rails-mocha#3]
I got some problems... first it's raising a warning:

```
*****************************************************************
DEPRECATION WARNING: you are using a deprecated constant that will
be removed from a future version of RSpec.

/Users/wilkersilva/.rvm/gems/ruby-1.9.2-p0/gems/bundler-1.0.3/lib/bundler/runtime.rb:64:in `require' 

* Rspec is deprecated.
* RSpec is the new top-level module in RSpec-2
***************************************************************
```

and them, it still not working, Im receiving this message:

```
3) products/edit.html.erb renders the edit product form
   Failure/Error: @product = assign(:product, stub_model(Product,
   undefined method `stub' for #<Product _id: 1001, name: "MyString", description: "MyText">
   # ./spec/views/products/edit.html.erb_spec.rb:5:in `block (2 levels) in <top (required)>'
```

its like its using old methods of RSpec mock

**Comment by mislav** [comment]
Just released version 0.2.1 that should fix the deprecation warning

As for the second error you're experiencing, I will need more info. How did you configure rspec-rails-mocha to be loaded? Second, does your project or included plugins use the `config.mock_with` directive in your specs?

**Comment by jfelchner** [comment]
Mislav, I'm getting the same error and yes, I have `config.mock_with :mocha` in `spec_helper`.  Anything I `stub_model` with throws this error.

Here's the full line causing the problem.

```
controller.stubs(:current_user).returns(stub_model(User, :email => 'whoami@example.com', :has_privileges? => true))
```

And here's my error:

```
undefined method `stub' for #<User:0x00000104da0688>
```

And looks like it's going here:

```
/Users/aspaulding/.rvm/gems/ruby-1.9.2-head@iris/gems/activerecord-3.0.3/lib/active_record/attribute_methods.rb:46:in `method_missing'
```

No matter if I have the gem installed or not.

**Comment by jfelchner** [comment]
Just tracked this down.  Looks like it's a ActiveRecord metaprogramming thing.  Still doing research.

**Comment by nicholasjhenry** [comment]
Confirmed I'm getting the same error with:

rspec (2.4.0)
rspec-rails (2.4.1)
rails (3.0.3)

**Comment by jfelchner** [comment]
All, I tracked it down and this is an RSpec issue first and _possibly_ an rspec-rails-mocha issue second.

You can follow the ticket on rspec-rails here: https://github.com/rspec/rspec-rails/issues#issue/310

**Comment by nicholasjhenry** [comment]
@jfelchner are you still pursuing this issue?

**Comment by jfelchner** [comment]
Indeed.  I've just been busy on the refactoring of another gem and haven't had time.  It's a quick fix.  I'll try to get it in this weekend.

**Comment by benhutton** [comment]
Any update on this?

**Comment by jfelchner** [comment]
Hey guys, I made a commit here: https://github.com/jfelchner/rspec-rails/commit/2c99e92ce029a4694f14a6e4dccb470a543344bb but I'm running into a fair bit of other issues regarding load order.  I think this is going to require a bigger change than originally anticipated.

**Comment by mislav** [comment]
Please see [my latest comment on #2](https://github.com/mislav/rspec-rails-mocha/issues/2#issuecomment-1393471)

The change in load order of rspec-rails is not needed for this. I worked around it. Follow my instructions exactly and let me know how it goes.

This is only for Rails 3. Rails 2 users should use the 0.2.x branch

**Comment by jfelchner** [comment]
@mislav, thanks for posting this. I've stopped using mocha but hopefully this will help everyone else out.  Regarding the RSpec load order; I think it's still an issue that the RSpec-specific mocks are getting loaded when RSpec is not the desired mocking framework.  But it's not a problem with rspec-rails-mocha and this seems to be a great interim solution.

Can anyone verify that Mislav's solution works to solve this issue?  If so, we'll close it out.

**Comment by nicholasjhenry** [comment]
@mislav, @jfelchner I have tested this with Rails 3.0.10 and spec-rails 2.6.1 and can confirm it works. Thanks mislav!
